image: node:18-alpine

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: 'Lint Testing'
              script:
                - yarn install --frozen-lockfile
                - 'yarn lint'
          - step:
              name: 'Unit Testing'
              script:
                - yarn install --frozen-lockfile
                - 'JEST_JUNIT_OUTPUT_DIR="test-reports/junit/" yarn test'
              artifacts:
                - ./test-reports/junit/junit.xml

  branches:
    <PRODBRANCH>:
      - step:
          name: 'Unit Testing'
          script:
            - yarn install --frozen-lockfile
            - 'JEST_JUNIT_OUTPUT_DIR="test-reports" yarn test'
